CI: azure
c_compiler: vs2019
channel_sources: conda-forge
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: vs2019
extend_keys:
- ignore_version
- pin_run_as_build
- extend_keys
- ignore_build_only_deps
fortran_compiler: gfortran
ignore_build_only_deps:
- numpy
- python
jpeg: '9'
libarchive: '3.5'
libpng: '1.6'
libtiff: '4'
libwebp: '1'
lua: '5'
numpy: '1.16'
openjpeg: '2.4'
perl: 5.26.2
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  jpeg:
    max_pin: x
  libpng:
    max_pin: x.x
  libtiff:
    max_pin: x
  openjpeg:
    max_pin: x.x
  zlib:
    max_pin: x.x
python: '3.9'
r_base: '3.4'
target_platform: win-64
vc: '14'
zlib: '1.2'
